# Securely store and access AWS credentials in development environments
brew "aws-vault"
# Mozilla CA certificate store
brew "ca-certificates"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# GitHub command-line tool
brew "gh"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# GNU typing tutor
brew "gnu-typist"
# Fast, distributed, high performance gradient boosting framework
brew "lightgbm"
# Polyglot runtime manager (asdf rust clone)
brew "mise"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Cross-shell prompt for astronauts
brew "starship"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Command-line interface for 1Password
cask "1password-cli"
# Chromium based browser
cask "arc"
# Compact TeX distribution as alternative to the full TeX Live / MacTeX
cask "basictex"
# Web browser focusing on privacy
cask "brave-browser"
# Tool to manage periodic breaks
cask "breaktimer"
# Open source IDE for exploring and testing APIs
cask "bruno"
# All-in-one toolbox for developers
cask "devutils"
# App to build and share containerised applications and microservices
cask "docker-desktop"
# Online diagram software
cask "drawio"
# Client for the Dropbox cloud storage service
cask "dropbox"
# Collaborative team software
cask "figma"
# Web browser
cask "firefox"
cask "font-fira-code-nerd-font"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Web browser
cask "google-chrome"
# Create custom keyboard shortcuts for anything
cask "keysmith"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Email client
cask "microsoft-outlook"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# VPN client
cask "mullvad-vpn"
# Geographic Information System
cask "qgis"
# Control your tools with a few keystrokes
cask "raycast"
# Team communication and collaboration software
cask "slack"
# Music streaming service
cask "spotify"
# Open-source BitTorrent client
cask "transmission"
# Open-source code editor
cask "visual-studio-code"
# Multimedia player
cask "vlc"
# Native desktop client for WhatsApp
cask "whatsapp"
# Collect, organise, cite, and share research sources
cask "zotero"
